### ISSUE TITLE
Error when try to run your example

### ISSUE THREAD

**Issue by badkaktus** [statistico/statistico-sportmonks-go-client#75]
Hello,

try to run

```go
package main

import (
	"context"
	"fmt"
	"github.com/statistico/statistico-sportmonks-go-client"
)

const SportmonksToken string = "TOKEN"

func main() {

	client := sportmonks.NewDefaultHTTPClient(SportmonksToken)

	league, _, err := client.LeagueByID(context.Background(), 271, []string{})

	if err != nil {
		fmt.Printf("%s\n", err.Error())
		return
	}

	fmt.Printf("%+v", league)
}
```

get an error:

```
C:\path\to\src>go run .
Lets start
json: cannot unmarshal bool into Go struct field LeagueCoverage.data.coverage.predictions of type int
```

is it bug or my problem? 

Thx

**Comment by joesweeny** [comment]
Hi @badkaktus apologies for such a delayed reply on this. Looking at the schema here: https://football-postman.sportmonks.com/#a27bc5b3-a6ed-4343-9e8d-97bd058dd698 you can see this field is meant to be a `boolean` value so this library implementation is correct.

I'm going to close this issue however if you do continue to have this issue please let me know and I will address it with Sportmonks direct.
